using Microsoft.AspNetCore.Mvc;
using NetCoreChatRoom.Models;
using NetCoreChatRoom.Models.NetCoreChatRoomAPIService.GroupChatMessage;
using NetCoreChatRoom.Services.Interfaces;
using Newtonsoft.Json;
using Serilog;

namespace NetCoreChatRoom.Components.GroupChatMessage
{
    public class GroupChatMessageViewComponent : ViewComponent
    {
        private readonly INetCoreChatRoomAPIService _netCoreChatRoomAPIService;
        private readonly AppSettingsModel _appSettingsModel;

        public GroupChatMessageViewComponent(INetCoreChatRoomAPIService netCoreChatRoomAPIService, AppSettingsModel appSettings)
        {
            _netCoreChatRoomAPIService = netCoreChatRoomAPIService;
            _appSettingsModel = appSettings;
        }

        public async Task<IViewComponentResult> InvokeAsync(int codGroupChat)
        {
            try
            {
                var inputModel = new GetLastGroupChatMessageModel(codGroupChat, _appSettingsModel.NetCoreChatRoomAPI.LastGroupChatMessageReturnQuantity);
                var model = await _netCoreChatRoomAPIService.GetLastGroupChatMessage(inputModel);

                #region test pouposes

                //var model = new ListGroupChatMessageModel();
                //model.AutoGenerateData(3);

                #endregion test pouposes

                return View(model);
            }
            catch (Exception ex)
            {
                Log.Error(JsonConvert.SerializeObject(ex));
                throw;
            }
        }
    }
}