using Microsoft.AspNetCore.Mvc;
using NetCoreChatRoom.Services.Interfaces;

namespace NetCoreChatRoom.Components.GroupChat
{
    public class GroupChatViewComponent : ViewComponent
    {
        private readonly INetCoreChatRoomAPIService _netCoreChatRoomAPIService;

        public GroupChatViewComponent(INetCoreChatRoomAPIService netCoreChatRoomAPIService)
        {
            _netCoreChatRoomAPIService = netCoreChatRoomAPIService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = await _netCoreChatRoomAPIService.GetAllGroupChat();

            #region test pourposes

            //var model = new ListGroupChatModel();
            //model.AutoGenerateData(2);

            #endregion test pourposes

            return View(model);
        }
    }
}